### ISSUE TITLE
Undefined class ImageStreamListener

### ISSUE THREAD

**Issue by xiang23** [CarGuo/GSYFlutterDemo#2]
![image](https://user-images.githubusercontent.com/14964761/60310130-f283cc00-9983-11e9-9c2b-4eca8e936a66.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

**Comment by xiang23** [comment]
看了下应是flutter版本与当前DEMO开发版本不一致导致的

**Comment by xiang23** [comment]
去隔壁项目看了下，保证flutter v1.6.3以上

**Comment by jp1017** [comment]
@CarGuo 尴尬了，不能用stable的吗

**Comment by jp1017** [comment]
暂时注释掉了相关代码，哈哈哈，先跑起来

**Comment by CarGuo** [comment]
哈哈哈，我喜欢用 beta 的 @jp1017 因为stable更新太慢了，现在 flutter 还是有不少问题， beta 更新的快一点
