### ISSUE TITLE
点击刷新demo，未刷新完成直接返回会造成崩溃

### ISSUE THREAD

**Issue by azhezzz** [CarGuo/GSYFlutterDemo#3]
### 复现步骤

*  点击 `简单上下刷新 例子`
*  未等刷新完成点击左上角`返回`
* `lib/widget/refrsh_demo_page.dart`中
![image](https://user-images.githubusercontent.com/31943269/60315206-31bc1800-9998-11e9-8733-6552d3b1da15.png)
其他例子我还没试过，不过可能也有类似问题

### 解决方法

* 建议在有可能出现调用`setState`时组件已注销的情况中
* 在调用`setState`前增加一个判断

![image](https://user-images.githubusercontent.com/31943269/60315392-0259db00-9999-11e9-88bb-868a0c32c61b.png)

**Comment by CarGuo** [comment]
嗯嗯，之前一直知道，只是这个报错其实不怎么影响，就懒得加上。
