### ISSUE TITLE
连续点击验证码输入框，键盘重复弹起

### ISSUE THREAD

**Issue by simplezhli** [CarGuo/GSYFlutterDemo#4]
[问题代码](https://github.com/CarGuo/GSYFlutterDemo/blob/master/lib/widget/verification_code_input_demo_page.dart#L208)，可以添加一个键盘弹出的判断来解决。

```dart
if (MediaQuery.of(context).viewInsets.bottom == 0){
   final focusScope = FocusScope.of(context);
   focusScope.requestFocus(FocusNode());
   Future.delayed(Duration.zero, () => focusScope.requestFocus(node));
}
```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYFlutterDemo/commit/8a9f5b9813ad7119e92a20f53b3cb34b986f618f
