### ISSUE TITLE
项目报错，有劳郭大

### ISSUE THREAD

**Issue by Rabbit95** [CarGuo/GSYFlutterDemo#7]
![image](https://user-images.githubusercontent.com/34308208/60500531-167d3f80-9ced-11e9-98ef-06c4aac8f107.png)

**Comment by Rabbit95** [comment]
不知道这个ImageStreamListener是哪里来的

**Comment by ldlywt** [comment]
升级到flutter 1.6.3就行了
通过下面这个命令查看你所在的渠道
$ flutter channel
Flutter channels:
* beta
  dev
  master

# 切换beta分支
$ flutter channel beta 

$ flutter upgrade

**Comment by Rabbit95** [comment]
> 升级到flutter 1.6.3就行了
> 通过下面这个命令查看你所在的渠道
> $ flutter channel
> Flutter channels:
> (*) beta
> dev
> master
> 
> 切换beta分支
> $ flutter channel beta
> 
> $ flutter upgrade

感谢！
